allowBuilds:
  '@prisma/engines': true
  msw: true
  prisma: true
  puppeteer: true
  sharp: true
  unrs-resolver: true
  zenstack: true
minimumReleaseAgeExclude:
  - '@better-auth/core@1.6.13'
  - '@better-auth/drizzle-adapter@1.6.13'
  - '@better-auth/kysely-adapter@1.6.13'
  - '@better-auth/memory-adapter@1.6.13'
  - '@better-auth/mongo-adapter@1.6.13'
  - '@better-auth/prisma-adapter@1.6.13'
  - '@better-auth/telemetry@1.6.13'
  - better-auth@1.6.13
overrides:
  kysely: "0.28.0"
